In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing   import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error, r2_score, mean_absolute_error

data = pd.read_csv('ventas_ml_clase2.csv')
display(data.head())

print(f"filas: {data.shape[0]}, columnas: {data.shape[1]}")

data.describe(include='all').transpose().head()

   marketing  precio  temporada     tienda   canal  ventas
0    5548.49   25.74          2        Sur  Tienda  461.70
1    3128.03   31.60          3  Occidente  Tienda  229.12
2    6350.81   37.94          3     Centro  Tienda  397.16
3    6693.02   34.28          3      Norte  Tienda  458.31
4    1488.14   30.45          1  Occidente  Tienda  197.70

filas: 1200, columnas: 6

            count unique     top freq  ...       25%       50%       75%       max
marketing  1200.0    NaN     NaN  NaN  ...  3772.115  5006.215  6107.785  10721.94
precio     1200.0    NaN     NaN  NaN  ...    29.915     34.91    39.245      55.4
temporada  1200.0    NaN     NaN  NaN  ...       2.0       3.0       3.0       4.0
tienda       1200      5   Norte  269  ...       NaN       NaN       NaN       NaN
canal        1200      3  Tienda  702  ...       NaN       NaN       NaN       NaN

[5 rows x 11 columns]

In [7]:
# predecir la ventas usuando variables: marketing, precio. temporada, tienda canal
X = data[['marketing', 'precio', 'temporada', 'tienda', 'canal']]
y = data['ventas']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42
)

print(f" Datos de entrenamiento: {X_train.shape[0]} filas, {X_train.shape[1]} columnas")
print(f" Datos de prueba: {X_test.shape[0]} filas, {X_test.shape[0]/len(X)*100:.0f}% del total") 
print()
print("el modelo aprendera con el 80% de los datos y se evaluara con el 20% restante")
print("Esto evitar que el modelo memorice los datos y permita evaluar su capacidad de generalización a nuevos datos")

 Datos de entrenamiento: 960 filas, 5 columnas
 Datos de prueba: 240 filas, 20% del total

el modelo aprendera con el 80% de los datos y se evaluara con el 20% restante
Esto evitar que el modelo memorice los datos y permita evaluar su capacidad de generalización a nuevos datos

In [14]:
numerical_features = ['marketing', 'precio', "temporada"]
categorical_features = ['tienda', 'canal']
Process = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)

    ]
)
model=LinearRegression()
pipe = Pipeline(steps=[
    ('preprocessor', Process),("model", model)])
    


pipe

NameError: name 'LinearRegression' is not defined